"""
Generated by _gen_data.py from the manual_angband425_broney data.  Do not edit
by hand; re-run the generator instead.

These tables are the single source of truth shared between generation (this
apworld) and the native game's APCc client.  Every location name is exactly the
string the client sends when the corresponding unique is killed / artifact is
picked up, and every item name is exactly the string the client receives.
"""

ITEM_ID_BASE = 4250000
LOCATION_ID_BASE = 4251000

# The dedicated, infinitely-repeatable filler item.
FILLER_ITEM_NAME = 'Piece of Elvish Waybread'

# The region the Victory event is placed in (the deepest dungeon band).
VICTORY_REGION = 'Depths 91-100'

# name -> AP item id
ITEM_NAME_TO_ID = {
    'Progressive Light Artifact': 4250001,
    'Progressive Bladed Weapon Artifact': 4250002,
    'Progressive Blunt Weapon Artifact': 4250003,
    'Progressive Polearm Weapon Artifact': 4250004,
    'Progressive Ranged Weapon Artifact': 4250005,
    'Pick of Erebor': 4250006,
    'Mattock of Náin': 4250007,
    'Progressive Boots Artifact': 4250008,
    'Progressive Helm Artifact': 4250009,
    'Progressive Armor Artifact': 4250010,
    'Progressive Cloak Artifact': 4250011,
    'Progressive Gloves Artifact': 4250012,
    'Progressive Shield Artifact': 4250013,
    'Progressive Ring Artifact': 4250014,
    'Progressive Amulet Artifact': 4250015,
    '2 Potions of Augmentation': 4250016,
    '+5 levels of Experience': 4250017,
    'Rod of Recall': 4250018,
    'Scroll of Acquirement': 4250019,
    'Scroll of Deep Descent': 4250020,
    'Triple Starting Gold': 4250021,
    'Expanded Starting Shop Books': 4250022,
    'Piece of Elvish Waybread': 4250023,
}

# name -> {count, classification, is_artifact}
ITEM_TABLE = {
    'Progressive Light Artifact': {
        'count': 3,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Bladed Weapon Artifact': {
        'count': 30,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Blunt Weapon Artifact': {
        'count': 12,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Polearm Weapon Artifact': {
        'count': 20,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Ranged Weapon Artifact': {
        'count': 6,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Pick of Erebor': {
        'count': 1,
        'classification': 'useful',
        'is_artifact': True,
    },
    'Mattock of Náin': {
        'count': 1,
        'classification': 'useful',
        'is_artifact': True,
    },
    'Progressive Boots Artifact': {
        'count': 6,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Helm Artifact': {
        'count': 10,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Armor Artifact': {
        'count': 13,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Cloak Artifact': {
        'count': 7,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Gloves Artifact': {
        'count': 9,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Shield Artifact': {
        'count': 6,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Ring Artifact': {
        'count': 6,
        'classification': 'progression',
        'is_artifact': True,
    },
    'Progressive Amulet Artifact': {
        'count': 5,
        'classification': 'progression',
        'is_artifact': True,
    },
    '2 Potions of Augmentation': {
        'count': 10,
        'classification': 'useful',
        'is_artifact': False,
    },
    '+5 levels of Experience': {
        'count': 10,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Rod of Recall': {
        'count': 4,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Scroll of Acquirement': {
        'count': 40,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Scroll of Deep Descent': {
        'count': 20,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Triple Starting Gold': {
        'count': 10,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Expanded Starting Shop Books': {
        'count': 2,
        'classification': 'useful',
        'is_artifact': False,
    },
    'Piece of Elvish Waybread': {
        'count': 0,
        'classification': 'filler',
        'is_artifact': False,
    },
}

# name -> AP location id
LOCATION_NAME_TO_ID = {
    'Farmer Maggot': 4251001,
    "Grip, Farmer Maggot's Dog": 4251002,
    "Fang, Farmer Maggot's Dog": 4251003,
    'Sméagol': 4251004,
    'Bullroarer the Hobbit': 4251005,
    'Mughash the Kobold Lord': 4251006,
    'Wormtongue, Agent of Saruman': 4251007,
    'Lagduf, the Snaga': 4251008,
    'Brodda, the Easterling': 4251009,
    'Orfax, Son of Boldor': 4251010,
    'Grishnákh, the Hill Orc': 4251011,
    'Golfimbul, the Hill Orc Chief': 4251012,
    'Boldor, King of the Yeeks': 4251013,
    'Ufthak of Cirith Ungol': 4251014,
    'Ulfast, Son of Ulfang': 4251015,
    'Nár, the Dwarf': 4251016,
    'Shagrat, the Orc Captain': 4251017,
    'Gorbag, the Orc Captain': 4251018,
    'Old Man Willow': 4251019,
    'Bolg, Son of Azog': 4251020,
    'Lugdush, the Uruk': 4251021,
    'Uglúk, the Uruk': 4251022,
    'Azog, Enemy of the Dwarves': 4251023,
    'Ibun, Son of Mîm': 4251024,
    'Khîm, Son of Mîm': 4251025,
    'Sangahyando of Umbar': 4251026,
    'Angamaitë of Umbar': 4251027,
    'Ulwarth, Son of Ulfang': 4251028,
    'Mîm, Betrayer of Turin': 4251029,
    'Uldor the Accursed': 4251030,
    'Draebor, the Imp': 4251031,
    'Beorn, the Shape-Changer': 4251032,
    'Bert the Stone Troll': 4251033,
    'Bill the Stone Troll': 4251034,
    'Tom the Stone Troll': 4251035,
    'Ulfang the Black': 4251036,
    'Lokkak, the Ogre Chieftain': 4251037,
    'Lorgan, Chief of the Easterlings': 4251038,
    'Castamir the Usurper': 4251039,
    'Gorlim, Betrayer of Barahir': 4251040,
    'Kavlax the Many-Headed': 4251041,
    'The Queen Ant': 4251042,
    'Rogrog the Black Troll': 4251043,
    'Vargo, Tyrant of Fire': 4251044,
    'Waldern, King of Water': 4251045,
    'Quaker, Master of Earth': 4251046,
    'Ariel, Queen of Air': 4251047,
    'Eöl, the Dark Elf': 4251048,
    'The Balrog of Moria': 4251049,
    'Harowen the Black Hand': 4251050,
    'Itangast the Fire Drake': 4251051,
    'Scatha the Worm': 4251052,
    'The Phoenix': 4251053,
    'Shelob, Spider of Darkness': 4251054,
    'Ar-Pharazôn the Golden': 4251055,
    'Baphomet the Minotaur Lord': 4251056,
    'Fundin Bluecloak': 4251057,
    'Gilim, the Giant of Eruman': 4251058,
    'Saruman of Many Colours': 4251059,
    'Smaug the Golden': 4251060,
    'The Mouth of Sauron': 4251061,
    'Tevildo, Prince of Cats': 4251062,
    'Thuringwethil, the Vampire Messenger': 4251063,
    'Tselakus, the Dreadlord': 4251064,
    'Nan, the Giant': 4251065,
    'Ossë, Herald of Ulmo': 4251066,
    'Omarax, the Eye Tyrant': 4251067,
    'Ungoliant, the Unlight': 4251068,
    'Glaurung, Father of the Dragons': 4251069,
    'Makar, the Warrior': 4251070,
    'Feagwath, the Undead Sorcerer': 4251071,
    'Uvatha the Horseman': 4251072,
    'Adunaphel the Quiet': 4251073,
    'Qlzqqlzuup, the Emperor Quylthulg': 4251074,
    'Akhorahil the Blind': 4251075,
    'Wiruin, the Maelstrom': 4251076,
    'Ren the Unclean': 4251077,
    'Maeglin, the Traitor of Gondolin': 4251078,
    'Ji Indur Dawndeath': 4251079,
    'Pazuzu, Lord of Air': 4251080,
    'Dwar, Dog Lord of Waw': 4251081,
    'Hoarmurath of Dir': 4251082,
    'Draugluin, Sire of All Werewolves': 4251083,
    'Khamûl, the Black Easterling': 4251084,
    'Cantoras, the Skeletal Lord': 4251085,
    'The Witch-King of Angmar': 4251086,
    'Ancalagon the Black': 4251087,
    'The Tarrasque': 4251088,
    'Meássë, the Bloody': 4251089,
    'Lungorthin, the Balrog of White Fire': 4251090,
    'Huan, Wolfhound of the Valar': 4251091,
    'Carcharoth, the Jaws of Thirst': 4251092,
    'Vecna, the Emperor Lich': 4251093,
    'Gothmog, the High Captain of Balrogs': 4251094,
    'Sauron, the Sorcerer': 4251095,
    'Morgoth, Lord of Darkness': 4251096,
    'Phial of Galadriel': 4251097,
    'Star of Elendil': 4251098,
    'Arkenstone of Thráin': 4251099,
    'Angrist': 4251100,
    'Narthanc': 4251101,
    'Nimthanc': 4251102,
    'Dethanc': 4251103,
    'Dagger of Rilia': 4251104,
    'Belangil': 4251105,
    'Main Gauche of Azaghâl': 4251106,
    'Main Gauche of Maedhros': 4251107,
    'Forasgil': 4251108,
    'Careth Asdriag': 4251109,
    'Sting': 4251110,
    'Dagmor': 4251111,
    'Gondricam': 4251112,
    'Haradekket': 4251113,
    'Ringil': 4251114,
    'Andúril': 4251115,
    'Anguirel': 4251116,
    'Elvagil': 4251117,
    'Aranrúth': 4251118,
    'Glamdring': 4251119,
    'Aeglin': 4251120,
    'Orcrist': 4251121,
    'Calris': 4251122,
    'Bastard Sword of Éowyn': 4251123,
    'Aglarang': 4251124,
    'Gurthang': 4251125,
    'Zarcuthra': 4251126,
    'Mormegil': 4251127,
    'Crisdurian': 4251128,
    'Doomcaller': 4251129,
    'Whip of Gothmog': 4251130,
    'Ball-and-Chain of Fundin Bluecloak': 4251131,
    'Bloodspike': 4251132,
    'Firestar': 4251133,
    'Totila': 4251134,
    'Thunderfist': 4251135,
    'Taratol': 4251136,
    'Nar-i-vagil': 4251137,
    'Eriril': 4251138,
    'Quarterstaff of Olórin': 4251139,
    'Great Hammer of Aulë': 4251140,
    'Deathwreaker': 4251141,
    'Aiglos': 4251142,
    'Spear of Oromë': 4251143,
    'Nimloth': 4251144,
    'Spear of Melkor': 4251145,
    'Trident of Wrath': 4251146,
    'Trident of Ulmo': 4251147,
    'Osondir': 4251148,
    'Til-i-arc': 4251149,
    'Beaked Axe of Théoden': 4251150,
    'Beaked Axe of Húrin': 4251151,
    'Barukkheled': 4251152,
    'Battle Axe of Balli Stonehand': 4251153,
    'Lotharang': 4251154,
    'Mundwine': 4251155,
    'Great Axe of Durin': 4251156,
    'Great Axe of Eönwë': 4251157,
    'Avavir': 4251158,
    'Glaive of Pain': 4251159,
    'Lance of the Eorlingas': 4251160,
    'Turmil': 4251161,
    'Short Bow of Amrod': 4251162,
    'Short Bow of Amras': 4251163,
    'Belthronding': 4251164,
    'Long Bow of Bard': 4251165,
    'Cubragol': 4251166,
    'Heavy Crossbow of Umbar': 4251167,
    'Pick of Erebor': 4251168,
    'Mattock of Náin': 4251169,
    'Pair of Leather Boots of Fëanor': 4251170,
    'Dal-i-thalion': 4251171,
    'Pair of Leather Boots of Wormtongue': 4251172,
    'Pair of Leather Boots of Radagast': 4251173,
    'Pair of Steel Shod Boots of Thrór': 4251174,
    'Stormwalker': 4251175,
    'Hard Leather Cap of Thranduil': 4251176,
    'Metal Cap of Thengel': 4251177,
    'Metal Cap of Celebrimbor': 4251178,
    'Iron Helm of Dor-Lómin': 4251179,
    'Holhenneth': 4251180,
    'Iron Helm of Gorlim': 4251181,
    'Steel Helm of Hammerhand': 4251182,
    'Iron Crown of Berúthiel': 4251183,
    'Golden Crown of Gondor': 4251184,
    'Jewel Encrusted Crown of Númenor': 4251185,
    'Hithlomir': 4251186,
    'Hard Leather Armour of Himring': 4251187,
    'Thalkettoth': 4251188,
    'Chain Mail of Arvedui': 4251189,
    'Augmented Chain Mail of Caspanion': 4251190,
    'Metal Brigandine Armour of the Rohirrim': 4251191,
    'Full Plate Armour of Isildur': 4251192,
    'Belegennon': 4251193,
    'Mithril Plate Mail of Celeborn': 4251194,
    'Soulkeeper': 4251195,
    'Colluin': 4251196,
    'Holcolleth': 4251197,
    'Cloak of Thingol': 4251198,
    'Cloak of Thorongil': 4251199,
    'Colannon': 4251200,
    'Elven Cloak of Lúthien': 4251201,
    'Ethereal Cloak of Tuor': 4251202,
    'Cambeleg': 4251203,
    'Cammithrim': 4251204,
    'Paurhach': 4251205,
    'Paurnimmen': 4251206,
    'Pauraegen': 4251207,
    'Paurnen': 4251208,
    'Camlost': 4251209,
    'Set of Gauntlets of Eöl': 4251210,
    'Set of Caestus of Fingolfin': 4251211,
    'Wicker Shield of Elros': 4251212,
    'Small Metal Shield of Thorin': 4251213,
    'Leather Shield of Celegorm': 4251214,
    'Leather Shield of the Haradrim': 4251215,
    'Large Metal Shield of Anárion': 4251216,
    "Knight's Shield of Eärendil": 4251217,
    'Mithril Shield of Gil-galad': 4251218,
    'Ring of Barahir': 4251219,
    'Band of Tulkas': 4251220,
    'Narya': 4251221,
    'Nenya': 4251222,
    'Vilya': 4251223,
    'Amulet of Carlammas': 4251224,
    'Pendant of Ingwë': 4251225,
    'Necklace of the Dwarves': 4251226,
    'Elessar': 4251227,
    'Evenstar': 4251228,
    'Razorback': 4251229,
    'Mediator': 4251230,
    'Bladeturner': 4251231,
    'The One Ring': 4251232,
}

# name -> {region, is_artifact}
LOCATION_TABLE = {
    'Farmer Maggot': {
        'region': 'Town',
        'is_artifact': False,
    },
    "Grip, Farmer Maggot's Dog": {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    "Fang, Farmer Maggot's Dog": {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Sméagol': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Bullroarer the Hobbit': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Mughash the Kobold Lord': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Wormtongue, Agent of Saruman': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Lagduf, the Snaga': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Brodda, the Easterling': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Orfax, Son of Boldor': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Grishnákh, the Hill Orc': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Golfimbul, the Hill Orc Chief': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Boldor, King of the Yeeks': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Ufthak of Cirith Ungol': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Ulfast, Son of Ulfang': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Nár, the Dwarf': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Shagrat, the Orc Captain': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Gorbag, the Orc Captain': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Old Man Willow': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Bolg, Son of Azog': {
        'region': 'Depths 1-20',
        'is_artifact': False,
    },
    'Lugdush, the Uruk': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Uglúk, the Uruk': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Azog, Enemy of the Dwarves': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Ibun, Son of Mîm': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Khîm, Son of Mîm': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Sangahyando of Umbar': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Angamaitë of Umbar': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Ulwarth, Son of Ulfang': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Mîm, Betrayer of Turin': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Uldor the Accursed': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Draebor, the Imp': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Beorn, the Shape-Changer': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Bert the Stone Troll': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Bill the Stone Troll': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Tom the Stone Troll': {
        'region': 'Depths 21-30',
        'is_artifact': False,
    },
    'Ulfang the Black': {
        'region': 'Depths 31-40',
        'is_artifact': False,
    },
    'Lokkak, the Ogre Chieftain': {
        'region': 'Depths 31-40',
        'is_artifact': False,
    },
    'Lorgan, Chief of the Easterlings': {
        'region': 'Depths 31-40',
        'is_artifact': False,
    },
    'Castamir the Usurper': {
        'region': 'Depths 31-40',
        'is_artifact': False,
    },
    'Gorlim, Betrayer of Barahir': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Kavlax the Many-Headed': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'The Queen Ant': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Rogrog the Black Troll': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Vargo, Tyrant of Fire': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Waldern, King of Water': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Quaker, Master of Earth': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Ariel, Queen of Air': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Eöl, the Dark Elf': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'The Balrog of Moria': {
        'region': 'Depths 41-50',
        'is_artifact': False,
    },
    'Harowen the Black Hand': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Itangast the Fire Drake': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Scatha the Worm': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'The Phoenix': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Shelob, Spider of Darkness': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Ar-Pharazôn the Golden': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Baphomet the Minotaur Lord': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Fundin Bluecloak': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Gilim, the Giant of Eruman': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Saruman of Many Colours': {
        'region': 'Depths 51-60',
        'is_artifact': False,
    },
    'Smaug the Golden': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'The Mouth of Sauron': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'Tevildo, Prince of Cats': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'Thuringwethil, the Vampire Messenger': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'Tselakus, the Dreadlord': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'Nan, the Giant': {
        'region': 'Depths 61-70',
        'is_artifact': False,
    },
    'Ossë, Herald of Ulmo': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Omarax, the Eye Tyrant': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Ungoliant, the Unlight': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Glaurung, Father of the Dragons': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Makar, the Warrior': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Feagwath, the Undead Sorcerer': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Uvatha the Horseman': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Adunaphel the Quiet': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Qlzqqlzuup, the Emperor Quylthulg': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Akhorahil the Blind': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Wiruin, the Maelstrom': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Ren the Unclean': {
        'region': 'Depths 71-80',
        'is_artifact': False,
    },
    'Maeglin, the Traitor of Gondolin': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Ji Indur Dawndeath': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Pazuzu, Lord of Air': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Dwar, Dog Lord of Waw': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Hoarmurath of Dir': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Draugluin, Sire of All Werewolves': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Khamûl, the Black Easterling': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Cantoras, the Skeletal Lord': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'The Witch-King of Angmar': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Ancalagon the Black': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'The Tarrasque': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Meássë, the Bloody': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Lungorthin, the Balrog of White Fire': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Huan, Wolfhound of the Valar': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Carcharoth, the Jaws of Thirst': {
        'region': 'Depths 81-90',
        'is_artifact': False,
    },
    'Vecna, the Emperor Lich': {
        'region': 'Depths 91-100',
        'is_artifact': False,
    },
    'Gothmog, the High Captain of Balrogs': {
        'region': 'Depths 91-100',
        'is_artifact': False,
    },
    'Sauron, the Sorcerer': {
        'region': 'Depths 91-100',
        'is_artifact': False,
    },
    'Morgoth, Lord of Darkness': {
        'region': 'Depths 91-100',
        'is_artifact': False,
    },
    'Phial of Galadriel': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Star of Elendil': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Arkenstone of Thráin': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Angrist': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Narthanc': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Nimthanc': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Dethanc': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Dagger of Rilia': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Belangil': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Main Gauche of Azaghâl': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Main Gauche of Maedhros': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Forasgil': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Careth Asdriag': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Sting': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Dagmor': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Gondricam': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Haradekket': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Ringil': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Andúril': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Anguirel': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Elvagil': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Aranrúth': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Glamdring': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Aeglin': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Orcrist': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Calris': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Bastard Sword of Éowyn': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Aglarang': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Gurthang': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Zarcuthra': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Mormegil': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Crisdurian': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Doomcaller': {
        'region': 'Depths 71-80',
        'is_artifact': True,
    },
    'Whip of Gothmog': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Ball-and-Chain of Fundin Bluecloak': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Bloodspike': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Firestar': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Totila': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Thunderfist': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Taratol': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Nar-i-vagil': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Eriril': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Quarterstaff of Olórin': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Great Hammer of Aulë': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Deathwreaker': {
        'region': 'Depths 81-90',
        'is_artifact': True,
    },
    'Aiglos': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Spear of Oromë': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Nimloth': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Spear of Melkor': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Trident of Wrath': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Trident of Ulmo': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Osondir': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Til-i-arc': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Beaked Axe of Théoden': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Beaked Axe of Húrin': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Barukkheled': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Battle Axe of Balli Stonehand': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Lotharang': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Mundwine': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Great Axe of Durin': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Great Axe of Eönwë': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Avavir': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Glaive of Pain': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Lance of the Eorlingas': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Turmil': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Short Bow of Amrod': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Short Bow of Amras': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Belthronding': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Long Bow of Bard': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Cubragol': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Heavy Crossbow of Umbar': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Pick of Erebor': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Mattock of Náin': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Pair of Leather Boots of Fëanor': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Dal-i-thalion': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Pair of Leather Boots of Wormtongue': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Pair of Leather Boots of Radagast': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Pair of Steel Shod Boots of Thrór': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Stormwalker': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Hard Leather Cap of Thranduil': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Metal Cap of Thengel': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Metal Cap of Celebrimbor': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Iron Helm of Dor-Lómin': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Holhenneth': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Iron Helm of Gorlim': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Steel Helm of Hammerhand': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Iron Crown of Berúthiel': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Golden Crown of Gondor': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Jewel Encrusted Crown of Númenor': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Hithlomir': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Hard Leather Armour of Himring': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Thalkettoth': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Chain Mail of Arvedui': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Augmented Chain Mail of Caspanion': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Metal Brigandine Armour of the Rohirrim': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Full Plate Armour of Isildur': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Belegennon': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Mithril Plate Mail of Celeborn': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Soulkeeper': {
        'region': 'Depths 71-80',
        'is_artifact': True,
    },
    'Colluin': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Holcolleth': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Cloak of Thingol': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Cloak of Thorongil': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Colannon': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Elven Cloak of Lúthien': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Ethereal Cloak of Tuor': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Cambeleg': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Cammithrim': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Paurhach': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Paurnimmen': {
        'region': 'Depths 21-30',
        'is_artifact': True,
    },
    'Pauraegen': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Paurnen': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Camlost': {
        'region': 'Depths 1-20',
        'is_artifact': True,
    },
    'Set of Gauntlets of Eöl': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Set of Caestus of Fingolfin': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Wicker Shield of Elros': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Small Metal Shield of Thorin': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Leather Shield of Celegorm': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Leather Shield of the Haradrim': {
        'region': 'Depths 31-40',
        'is_artifact': True,
    },
    'Large Metal Shield of Anárion': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    "Knight's Shield of Eärendil": {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Mithril Shield of Gil-galad': {
        'region': 'Depths 71-80',
        'is_artifact': True,
    },
    'Ring of Barahir': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Band of Tulkas': {
        'region': 'Depths 71-80',
        'is_artifact': True,
    },
    'Narya': {
        'region': 'Depths 71-80',
        'is_artifact': True,
    },
    'Nenya': {
        'region': 'Depths 81-90',
        'is_artifact': True,
    },
    'Vilya': {
        'region': 'Depths 91-100',
        'is_artifact': True,
    },
    'Amulet of Carlammas': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Pendant of Ingwë': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Necklace of the Dwarves': {
        'region': 'Depths 51-60',
        'is_artifact': True,
    },
    'Elessar': {
        'region': 'Depths 61-70',
        'is_artifact': True,
    },
    'Evenstar': {
        'region': 'Depths 41-50',
        'is_artifact': True,
    },
    'Razorback': {
        'region': 'Depths 91-100',
        'is_artifact': True,
    },
    'Mediator': {
        'region': 'Depths 91-100',
        'is_artifact': True,
    },
    'Bladeturner': {
        'region': 'Depths 91-100',
        'is_artifact': True,
    },
    'The One Ring': {
        'region': 'Depths 91-100',
        'is_artifact': True,
    },
}

# region name -> {connects_to, requires:[[item,count]...], starting}
REGION_TABLE = {
    'Town': {
        'connects_to': ['Depths 1-20'],
        'requires': [],
        'starting': True,
    },
    'Depths 1-20': {
        'connects_to': ['Depths 21-30'],
        'requires': [],
        'starting': True,
    },
    'Depths 21-30': {
        'connects_to': ['Depths 31-40'],
        'requires': [['Progressive Light Artifact', 1], ['Progressive Bladed Weapon Artifact', 4]],
        'starting': False,
    },
    'Depths 31-40': {
        'connects_to': ['Depths 41-50'],
        'requires': [
            ['Progressive Light Artifact', 1],
            ['Progressive Bladed Weapon Artifact', 4],
            ['Progressive Blunt Weapon Artifact', 1],
            ['Progressive Polearm Weapon Artifact', 1],
            ['Progressive Helm Artifact', 1],
            ['Progressive Armor Artifact', 2],
        ],
        'starting': False,
    },
    'Depths 41-50': {
        'connects_to': ['Depths 51-60'],
        'requires': [
            ['Progressive Light Artifact', 1],
            ['Progressive Bladed Weapon Artifact', 8],
            ['Progressive Blunt Weapon Artifact', 3],
            ['Progressive Polearm Weapon Artifact', 4],
            ['Progressive Ranged Weapon Artifact', 2],
            ['Progressive Boots Artifact', 2],
            ['Progressive Helm Artifact', 2],
            ['Progressive Armor Artifact', 4],
            ['Progressive Cloak Artifact', 2],
            ['Progressive Gloves Artifact', 2],
            ['Progressive Shield Artifact', 1],
            ['Progressive Ring Artifact', 1],
            ['Progressive Amulet Artifact', 1],
        ],
        'starting': False,
    },
    'Depths 51-60': {
        'connects_to': ['Depths 61-70'],
        'requires': [
            ['Progressive Light Artifact', 2],
            ['Progressive Bladed Weapon Artifact', 12],
            ['Progressive Blunt Weapon Artifact', 4],
            ['Progressive Polearm Weapon Artifact', 6],
            ['Progressive Ranged Weapon Artifact', 2],
            ['Progressive Boots Artifact', 2],
            ['Progressive Helm Artifact', 3],
            ['Progressive Armor Artifact', 5],
            ['Progressive Cloak Artifact', 2],
            ['Progressive Gloves Artifact', 3],
            ['Progressive Shield Artifact', 2],
            ['Progressive Ring Artifact', 2],
            ['Progressive Amulet Artifact', 3],
        ],
        'starting': False,
    },
    'Depths 61-70': {
        'connects_to': ['Depths 71-80'],
        'requires': [
            ['Progressive Light Artifact', 3],
            ['Progressive Bladed Weapon Artifact', 14],
            ['Progressive Blunt Weapon Artifact', 6],
            ['Progressive Polearm Weapon Artifact', 8],
            ['Progressive Ranged Weapon Artifact', 3],
            ['Progressive Boots Artifact', 3],
            ['Progressive Helm Artifact', 4],
            ['Progressive Armor Artifact', 7],
            ['Progressive Cloak Artifact', 3],
            ['Progressive Gloves Artifact', 4],
            ['Progressive Shield Artifact', 3],
            ['Progressive Ring Artifact', 4],
            ['Progressive Amulet Artifact', 3],
        ],
        'starting': False,
    },
    'Depths 71-80': {
        'connects_to': ['Depths 81-90'],
        'requires': [
            ['Progressive Bladed Weapon Artifact', 18],
            ['Progressive Blunt Weapon Artifact', 8],
            ['Progressive Polearm Weapon Artifact', 12],
            ['Progressive Ranged Weapon Artifact', 3],
            ['Progressive Boots Artifact', 3],
            ['Progressive Helm Artifact', 5],
            ['Progressive Armor Artifact', 8],
            ['Progressive Cloak Artifact', 4],
            ['Progressive Gloves Artifact', 4],
            ['Progressive Shield Artifact', 3],
            ['Progressive Ring Artifact', 4],
            ['Progressive Amulet Artifact', 4],
        ],
        'starting': False,
    },
    'Depths 81-90': {
        'connects_to': ['Depths 91-100'],
        'requires': [
            ['Progressive Bladed Weapon Artifact', 22],
            ['Progressive Blunt Weapon Artifact', 9],
            ['Progressive Polearm Weapon Artifact', 14],
            ['Progressive Ranged Weapon Artifact', 4],
            ['Progressive Boots Artifact', 4],
            ['Progressive Helm Artifact', 7],
            ['Progressive Armor Artifact', 10],
            ['Progressive Cloak Artifact', 6],
            ['Progressive Gloves Artifact', 6],
            ['Progressive Shield Artifact', 5],
            ['Progressive Ring Artifact', 4],
            ['Progressive Amulet Artifact', 4],
        ],
        'starting': False,
    },
    'Depths 91-100': {
        'connects_to': [],
        'requires': [
            ['Progressive Bladed Weapon Artifact', 28],
            ['Progressive Blunt Weapon Artifact', 10],
            ['Progressive Polearm Weapon Artifact', 18],
            ['Progressive Ranged Weapon Artifact', 5],
            ['Progressive Boots Artifact', 6],
            ['Progressive Helm Artifact', 10],
            ['Progressive Armor Artifact', 13],
            ['Progressive Cloak Artifact', 7],
            ['Progressive Gloves Artifact', 8],
            ['Progressive Shield Artifact', 6],
            ['Progressive Ring Artifact', 5],
            ['Progressive Amulet Artifact', 5],
        ],
        'starting': False,
    },
}
